export enum AppErrorCode {
  // Umum
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  INVALID_STATE_TRANSITION = 'INVALID_STATE_TRANSITION',
  TENANT_ACCESS_DENIED = 'TENANT_ACCESS_DENIED',
  TENANT_REQUIRED = 'TENANT_REQUIRED',
  TENANT_ROLE_INSUFFICIENT = 'TENANT_ROLE_INSUFFICIENT',
  ALREADY_OWNED = 'ALREADY_OWNED',
  PAYMENT_EXPIRED = 'PAYMENT_EXPIRED',
  PAYMENT_PROVIDER_UNAVAILABLE = 'PAYMENT_PROVIDER_UNAVAILABLE',
  OWNERSHIP_DENIED = 'OWNERSHIP_DENIED',
  ENTITLEMENT_REQUIRED = 'ENTITLEMENT_REQUIRED',
  CONTENT_NOT_PUBLISHED = 'CONTENT_NOT_PUBLISHED',
  CONTENT_LOCKED = 'CONTENT_LOCKED',
  CLASS_FULL = 'CLASS_FULL',
  PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND',
  PAYMENT_ALREADY_REVIEWED = 'PAYMENT_ALREADY_REVIEWED',
  INVALID_PAYMENT_STATE = 'INVALID_PAYMENT_STATE',
  INVALID_ORDER_STATE = 'INVALID_ORDER_STATE',
  INSUFFICIENT_AI_CREDITS = 'INSUFFICIENT_AI_CREDITS',
  AI_CREDIT_RESERVATION_FAILED = 'AI_CREDIT_RESERVATION_FAILED',
  PAYOUT_EXCEEDS_BALANCE = 'PAYOUT_EXCEEDS_BALANCE',
  REFUND_EXCEEDS_BALANCE = 'REFUND_EXCEEDS_BALANCE',
  UNAUTHORIZED_TOOL = 'UNAUTHORIZED_TOOL',
  AGENT_BUDGET_EXCEEDED = 'AGENT_BUDGET_EXCEEDED',
  NOT_FOUND = 'NOT_FOUND',

  EMAIL_VERIFICATION_FAILED = 'EMAIL_VERIFICATION_FAILED',
  INVALID_OTP = 'INVALID_OTP',
  EXPIRED_OTP = 'EXPIRED_OTP',
  EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED',


  RESEND_ERROR = 'RESEND_ERROR',
  EMAIL_SEND_FAILED = 'EMAIL_SEND_FAILED',

  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',

  DB_CONNECTION_ERROR = 'DB_CONNECTION_ERROR',
  UNIQUE_CONSTRAINT_FAILED = 'UNIQUE_CONSTRAINT_FAILED',

  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
}

export class AppError extends Error {
  constructor(
    public readonly message: string,
    public readonly statusCode: number = 500,
    public readonly code: AppErrorCode = AppErrorCode.INTERNAL_SERVER_ERROR
  ) {
    super(message);
    this.name = 'AppError';
  }
}
