import z from "zod";
import { extendApi } from "@anatine/zod-openapi";

export const baseUserStepSchema = z.object({
  userId: z.string().uuid("User ID must be a valid UUID").describe("Related User ID"),
  stepTemplateId: z.string().uuid().optional().nullable().describe("Optional template step ID"),
  title: z.string().min(1).describe("Step title"),
  quizId: z.string().uuid().optional().nullable().describe("Related Quiz ID"),
  isDone: z.boolean().default(false).describe("Completion status"),
  order: z.number().describe("order number"),
  isUnlocked:z.boolean().default(false).describe("uncloked status"),
  createdAt: z.date().default(new Date()).describe("Creation date and time"),
  updatedAt: z.date().optional().nullable().describe("Last update date and time"),
});

export const CreateUserStepDto = extendApi(
  z.union([baseUserStepSchema, z.array(baseUserStepSchema)]),
  {
    title: "CreateUserStepDto",
    example: [
      {
        userId: "uuid-user-1234",
        stepTemplateId: "uuid-step-5678",
        title: "Learn TypeScript Basics",
        quizId: "uuid-quiz-1111",
        isDone: false,
        order:1,
        isUnlocked:true,
        createdAt: "2025-11-20T04:00:00Z"
      },
      {
        userId: "uuid-user-9999",
        title: "Advanced Prisma Relations",
        description: "Custom step generated by AI",
        quizId: null,
        isDone: true,
        isUnlocked:false,
        order:2,
        createdAt: "2025-11-18T09:00:00Z",
        updatedAt: "2025-11-19T12:00:00Z"
      }
    ]
  }
);

export type CreateUserStepType = z.infer<typeof CreateUserStepDto>;

export const UpdateUserStepDto = extendApi(
  baseUserStepSchema.partial(),
  {
    title: "UpdateUserStepDto",
    example: {
      title: "Updated Step Title",
      description: "Updated description",
      quizId: "uuid-quiz-1111",
      isDone: true,
      isUnlocked:true
    }
  }
);

export type UpdateUserStepType = z.infer<typeof UpdateUserStepDto>;
